:guid: %guid%
:user: %user%
:ssh_command: %ssh_password%
:bastion_public_hostname: %bastion_public_hostname%
:bastion_ssh_user_name: %bastion_ssh_user_name%
:bastion_ssh_password: %bastion_ssh_password%
:openshift-console-url: %openshift_console_url%
:openshift-api-url: %openshift_api_url%
:openshift-cluster-ingress-domain: %openshift_cluster_ingress_domain%
:openshift-kubeadmin-password: %openshift_kubeadmin_password%
:markup-in-source: verbatim,attributes,quotes

== Overview

This lab gives a hands on experience on how to use Kepler to measure container energy consumption.

== Intro

About Kepler

TO-DO

== Command Line Access to Bastion Host

To do this lab, it's preferable to use command line access to the OpenShift cluster.
You've been provided a "bastion host" that preconfigured with everything you'll need to complete the lab.
Complete the following steps to prepare for the lab.

. Access your lab environment as {user} with password "{ssh_password}" with the following command:
+
[source,bash,options="nowrap",subs="{markup-in-source}",role=execute]
----
ssh {bastion_ssh_user_name}@{bastion_public_hostname}
----

. Accept the new secrets and enter the ssh password
+
[source,bash,options="nowrap",subs="{markup-in-source}",role=execute]
----
{bastion_ssh_password}
----

Your lab GUID is "{guid}".

== OpenShift Console Access

You'll also need to access the OpenShift Console in this lab.
Log into the OpenShift Console with the following commands.

. Access your {openshift-console-url}[OpenShift Console^].

. Log in with username `kubeadmin` and password `{openshift-kubeadmin-password}`
